### ISSUE TITLE
After exporting the lang folder has to be inside the root folder

### ISSUE THREAD

**Issue by kleingulo** [Creta5164/L10nMV.js#4] opened 2021-11-29 18:32 UTC
The readme says to put the the lang folder inside the project folder. Testplay in engine works fine but after exporting the game it doesn't find the files anymore (according to the console).
I have to move the lang folder in the root folder to make it work.

Edit:
Actually it has to be in both??? places to work

**Comment by Creta5164** [comment] 2021-12-06 05:06
Short answer is : You must do copy `lang` directory to builded game's `www` root.

<img src="https://user-images.githubusercontent.com/13521406/144790259-4123bb3c-c95d-4b31-a841-60c137fe216a.png" width="500"/>
  
It's a problem I can't solve, as **RPG Maker can't create a configuration for a build pipeline that I can define for this**.  
Please understand what this is about.

---

In order to solve this problem, [Causality][0], a production-level project that I participated in, created it's own build tool as shown below to run post-processing separately and manually.

![image](https://user-images.githubusercontent.com/13521406/144790049-1e75b1d0-0c25-4d86-8c90-fe25a0a40240.png)

\* You can read my post-mortem about this in [here][1]. (Korean, use Chrome to translate it)

I will close this issue.

[0]: https://store.steampowered.com/app/1158720
[1]: https://creft.me/p/causality-game/post-mortem

**Comment by kleingulo** [comment] 2021-12-06 16:29
Thats odd, because I fixed it myself by replacing this line:
`L10nMV.LANG_ROOT="./lang/";`
with this line:
`L10nMV.LANG_ROOT=(Utils.isNwjs() && Utils.isOptionValid("test")) ? "./lang/" : process.cwd() + "/www/lang/";`

**Comment by Creta5164** [comment] 2021-12-09 06:49
Can you check whether the following two conditions are satisfied?

- Can you describe your environment? (OS, RPG Maker version, NW version, project directory structure)  
  This helps me validate the situation and address the issues.
- Is this issue can re-implemented in the clean project (new project)?  
  This condition is because, in my principle, it want be original source code does not depend on a specific environment and method.  
  If you have added a special structure and behavior to the project, you can use it by modifying it as given in the answer now.

If these two conditions are satisfied, I will check this issue.  
Otherwise, if your solution is added to the structure and environment of the project, please feel free to modify it and use it.

**Comment by Creta5164** [comment] 2022-01-29 08:05
*Closing an issue after a long period of inactivity.*

**Closed as completed by Creta5164** 2022-01-29 08:05 UTC
Labels: bug

**Comment by Creta5164** [comment] 2022-01-30 07:16
Finally able to reproduce this issue, `1.4.6` will publish soon.

**Comment by Creta5164** [comment] 2022-02-08 05:31
Fixed in `1.4.6`
